# Generated by Django 4.1.7 on 2023-03-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogger',
            old_name='posts_cout',
            new_name='posts_count',
        ),
    ]
